version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-RadioApi
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - radioapi_data:/var/lib/mysql


volumes:
  radioapi_data: