spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: ${JDBC_DATABASE_URL}
    username: foo
    password: bar
    driverClassName: org.postgresql.Driver
