spring:
  datasource:
    url: ${DATABASE_URL}
    user: ${USER}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        ddl-auto: update